-- MySQL Script generated by MySQL Workbench
-- Mon Apr 20 16:44:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema farmacos_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmacos_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmacos_bd` DEFAULT CHARACTER SET utf8 ;
USE `farmacos_bd` ;

-- -----------------------------------------------------
-- Table `farmacos_bd`.`medicamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacos_bd`.`medicamentos` ;

CREATE TABLE IF NOT EXISTS `farmacos_bd`.`medicamentos` (
  `codigoNacional` INT NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `viaAdministracion` VARCHAR(100) NOT NULL,
  `presentacion` VARCHAR(100) NULL DEFAULT NULL,
  `formato` VARCHAR(100) NULL DEFAULT NULL,
  `claseMedicamento` VARCHAR(105) NULL DEFAULT NULL,
  `indicaciones` VARCHAR(100) NULL DEFAULT NULL,
  `comercializacion` TINYINT NULL DEFAULT NULL,
  `prescripcionMedica` TINYINT NULL DEFAULT NULL,
  `pvp` FLOAT NOT NULL,
  PRIMARY KEY (`codigoNacional`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `farmacos_bd`.`principios_activos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacos_bd`.`principios_activos` ;

CREATE TABLE IF NOT EXISTS `farmacos_bd`.`principios_activos` (
  `Nombre` VARCHAR(60) NOT NULL,
  `pesoMolecular` FLOAT NULL DEFAULT NULL,
  `formulaMolecular` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `farmacos_bd`.`med_tienen_pa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacos_bd`.`med_tienen_pa` ;

CREATE TABLE IF NOT EXISTS `farmacos_bd`.`med_tienen_pa` (
  `MEDICAMENTOS_codigoNacional` INT NOT NULL,
  `PRINCIPIOSACTIVOS_nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`MEDICAMENTOS_codigoNacional`, `PRINCIPIOSACTIVOS_nombre`),
  INDEX `fk_medicamentos_has_principios_activos_principios_activos1_idx` (`PRINCIPIOSACTIVOS_nombre` ASC) VISIBLE,
  INDEX `fk_medicamentos_has_principios_activos_medicamentos_idx` (`MEDICAMENTOS_codigoNacional` ASC) VISIBLE,
  CONSTRAINT `fk_medicamentos_has_principios_activos_medicamentos`
    FOREIGN KEY (`MEDICAMENTOS_codigoNacional`)
    REFERENCES `farmacos_bd`.`medicamentos` (`codigoNacional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamentos_has_principios_activos_principios_activos1`
    FOREIGN KEY (`PRINCIPIOSACTIVOS_nombre`)
    REFERENCES `farmacos_bd`.`principios_activos` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
